puts "applying partitioning constraints generated by tapac"
write_checkpoint before_add_floorplan_constraints.dcp

# begin defining a slot
create_pblock CR_X0Y0_To_CR_X3Y3
resize_pblock CR_X0Y0_To_CR_X3Y3 -add CLOCKREGION_X0Y0:CLOCKREGION_X3Y3
# remove the reserved clock regions for the Vitis infra
resize_pblock CR_X0Y0_To_CR_X3Y3 -remove CLOCKREGION_X7Y1:CLOCKREGION_X7Y11


# begin defining a slot
create_pblock CR_X4Y0_To_CR_X7Y3
resize_pblock CR_X4Y0_To_CR_X7Y3 -add CLOCKREGION_X4Y0:CLOCKREGION_X7Y3
# remove the reserved clock regions for the Vitis infra
resize_pblock CR_X4Y0_To_CR_X7Y3 -remove CLOCKREGION_X7Y1:CLOCKREGION_X7Y11

add_cells_to_pblock [get_pblocks pblock_dynamic_SLR0] [get_cells -regex {
  pfm_top_i/dynamic_region/.*/inst/.*/control_s_axi_U_slr_0
  pfm_top_i/dynamic_region/.*/inst/.*/tapa_state.*
} ]
add_cells_to_pblock [get_pblocks pblock_dynamic_SLR1] [get_cells -regex {
  pfm_top_i/dynamic_region/.*/inst/.*/control_s_axi_U_slr_1
} ]
add_cells_to_pblock [get_pblocks pblock_dynamic_SLR2] [get_cells -regex {
  pfm_top_i/dynamic_region/.*/inst/.*/control_s_axi_U_slr_2
} ]
add_cells_to_pblock [get_pblocks CR_X4Y0_To_CR_X7Y3] [get_cells -regex {
  pfm_top_i/dynamic_region/.*/inst/.*/Mmap2Stream_b_0
  pfm_top_i/dynamic_region/.*/inst/.*/Mmap2Stream_b_0__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/Mmap2Stream_values_0
  pfm_top_i/dynamic_region/.*/inst/.*/Mmap2Stream_values_0__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/Mmap2Stream_values_1
  pfm_top_i/dynamic_region/.*/inst/.*/Mmap2Stream_values_1__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/Mmap2Stream_values_2
  pfm_top_i/dynamic_region/.*/inst/.*/Mmap2Stream_values_2__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/Mmap2Stream_values_3
  pfm_top_i/dynamic_region/.*/inst/.*/Mmap2Stream_values_3__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/Stream2Mmap_solvedX_0
  pfm_top_i/dynamic_region/.*/inst/.*/Stream2Mmap_solvedX_0__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/b_stream_0/inst\\[0]\\.unit
  pfm_top_i/dynamic_region/.*/inst/.*/colIdx_stream_0/inst\\[0]\\.unit
  pfm_top_i/dynamic_region/.*/inst/.*/colIdx_stream_1/inst\\[0]\\.unit
  pfm_top_i/dynamic_region/.*/inst/.*/colIdx_stream_2/inst\\[0]\\.unit
  pfm_top_i/dynamic_region/.*/inst/.*/colIdx_stream_3/inst\\[0]\\.unit
  pfm_top_i/dynamic_region/.*/inst/.*/tlast_stream_0/inst\\[0]\\.unit
  pfm_top_i/dynamic_region/.*/inst/.*/tlast_stream_1/inst\\[0]\\.unit
  pfm_top_i/dynamic_region/.*/inst/.*/tlast_stream_2/inst\\[0]\\.unit
  pfm_top_i/dynamic_region/.*/inst/.*/tlast_stream_3/inst\\[0]\\.unit
  pfm_top_i/dynamic_region/.*/inst/.*/val_stream_0/inst\\[0]\\.unit
  pfm_top_i/dynamic_region/.*/inst/.*/val_stream_1/inst\\[0]\\.unit
  pfm_top_i/dynamic_region/.*/inst/.*/val_stream_2/inst\\[0]\\.unit
  pfm_top_i/dynamic_region/.*/inst/.*/val_stream_3/inst\\[0]\\.unit
  pfm_top_i/dynamic_region/.*/inst/.*/x_out_stream/inst\\[1]\\.unit
} ]
add_cells_to_pblock [get_pblocks CR_X0Y0_To_CR_X3Y3] [get_cells -regex {
  pfm_top_i/dynamic_region/.*/inst/.*/dummyBConsume_0
  pfm_top_i/dynamic_region/.*/inst/.*/dummyBConsume_0__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/manage_x_0
  pfm_top_i/dynamic_region/.*/inst/.*/manage_x_0__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/sptrsv_PE_0
  pfm_top_i/dynamic_region/.*/inst/.*/sptrsv_PE_0__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/sptrsv_PE_1
  pfm_top_i/dynamic_region/.*/inst/.*/sptrsv_PE_1__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/sptrsv_PE_2
  pfm_top_i/dynamic_region/.*/inst/.*/sptrsv_PE_2__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/sptrsv_PE_3
  pfm_top_i/dynamic_region/.*/inst/.*/sptrsv_PE_3__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/b_stream_0/inst\\[1]\\.unit
  pfm_top_i/dynamic_region/.*/inst/.*/b_stream_1/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/b_stream_2/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/b_stream_3/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/b_stream_4/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/colIdx_stream_0/inst\\[1]\\.unit
  pfm_top_i/dynamic_region/.*/inst/.*/colIdx_stream_1/inst\\[1]\\.unit
  pfm_top_i/dynamic_region/.*/inst/.*/colIdx_stream_2/inst\\[1]\\.unit
  pfm_top_i/dynamic_region/.*/inst/.*/colIdx_stream_3/inst\\[1]\\.unit
  pfm_top_i/dynamic_region/.*/inst/.*/tlast_stream_0/inst\\[1]\\.unit
  pfm_top_i/dynamic_region/.*/inst/.*/tlast_stream_1/inst\\[1]\\.unit
  pfm_top_i/dynamic_region/.*/inst/.*/tlast_stream_2/inst\\[1]\\.unit
  pfm_top_i/dynamic_region/.*/inst/.*/tlast_stream_3/inst\\[1]\\.unit
  pfm_top_i/dynamic_region/.*/inst/.*/val_stream_0/inst\\[1]\\.unit
  pfm_top_i/dynamic_region/.*/inst/.*/val_stream_1/inst\\[1]\\.unit
  pfm_top_i/dynamic_region/.*/inst/.*/val_stream_2/inst\\[1]\\.unit
  pfm_top_i/dynamic_region/.*/inst/.*/val_stream_3/inst\\[1]\\.unit
  pfm_top_i/dynamic_region/.*/inst/.*/x_out_stream/inst\\[0]\\.unit
  pfm_top_i/dynamic_region/.*/inst/.*/x_req_address_stream_0/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/x_req_address_stream_1/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/x_req_address_stream_2/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/x_req_address_stream_3/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/x_resp_val_stream_0/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/x_resp_val_stream_1/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/x_resp_val_stream_2/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/x_resp_val_stream_3/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/x_solved_colIdx_stream_0/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/x_solved_colIdx_stream_1/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/x_solved_colIdx_stream_2/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/x_solved_colIdx_stream_3/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/x_solved_val_stream_0/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/x_solved_val_stream_1/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/x_solved_val_stream_2/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/x_solved_val_stream_3/.*.unit
} ]
foreach pblock [get_pblocks -regexp CR_X\\d+Y\\d+_To_CR_X\\d+Y\\d+] {
  if {[get_property CELL_COUNT $pblock] == 0} {
    puts "WARNING: delete empty pblock $pblock "
    delete_pblocks $pblock
  }
}
foreach pblock [get_pblocks] {
  report_utilization -pblocks $pblock
}